--- Day 7: Camel Cards ---

Your all-expenses-paid trip turns out to be a one-way, five-minute ride in an airship. (At least it's a cool airship!) It drops you off at the edge of a vast desert and descends back to Island Island.

"Did you bring the parts?"

You turn around to see an Elf completely covered in white clothing, wearing goggles, and riding a large camel.

"Did you bring the parts?" she asks again, louder this time. You aren't sure what parts she's looking for; you're here to figure out why the sand stopped.

"The parts! For the sand, yes! Come with me; I will show you." She beckons you onto the camel.

After riding a bit across the sands of Desert Island, you can see what look like very large rocks covering half of the horizon. The Elf explains that the rocks are all along the part of Desert Island that is directly above Island Island, making it hard to even get there. Normally, they use big machines to move the rocks and filter the sand, but the machines have broken down because Desert Island recently stopped receiving the parts they need to fix the machines.

You've already assumed it'll be your job to figure out why the parts stopped when she asks if you can help. You agree automatically.

Because the journey will take a few days, she offers to teach you the game of Camel Cards. Camel Cards is sort of similar to poker except it's designed to be easier to play while riding a camel.

In Camel Cards, you get a list of hands, and your goal is to order them based on the strength of each hand. A hand consists of five cards labeled one of A, K, Q, J, T, 9, 8, 7, 6, 5, 4, 3, or 2. The relative strength of each card follows this order, where A is the highest and 2 is the lowest.

Every hand is exactly one type. From strongest to weakest, they are:

Five of a kind, where all five cards have the same label: AAAAA
Four of a kind, where four cards have the same label and one card has a different label: AA8AA
Full house, where three cards have the same label, and the remaining two cards share a different label: 23332
Three of a kind, where three cards have the same label, and the remaining two cards are each different from any other card in the hand: TTT98
Two pair, where two cards share one label, two other cards share a second label, and the remaining card has a third label: 23432
One pair, where two cards share one label, and the other three cards have a different label from the pair and each other: A23A4
High card, where all cards' labels are distinct: 23456
Hands are primarily ordered based on type; for example, every full house is stronger than any three of a kind.

If two hands have the same type, a second ordering rule takes effect. Start by comparing the first card in each hand. If these cards are different, the hand with the stronger first card is considered stronger. If the first card in each hand have the same label, however, then move on to considering the second card in each hand. If they differ, the hand with the higher second card wins; otherwise, continue with the third card in each hand, then the fourth, then the fifth.

So, 33332 and 2AAAA are both four of a kind hands, but 33332 is stronger because its first card is stronger. Similarly, 77888 and 77788 are both a full house, but 77888 is stronger because its third card is stronger (and both hands have the same first and second card).

To play Camel Cards, you are given a list of hands and their corresponding bid (your puzzle input). For example:

```
32T3K 765
T55J5 684
KK677 28
KTJJT 220
QQQJA 483
```

This example shows five hands; each hand is followed by its bid amount. Each hand wins an amount equal to its bid multiplied by its rank, where the weakest hand gets rank 1, the second-weakest hand gets rank 2, and so on up to the strongest hand. Because there are five hands in this example, the strongest hand will have rank 5 and its bid will be multiplied by 5.

So, the first step is to put the hands in order of strength:

- 32T3K is the only one pair and the other hands are all a stronger type, so it gets rank 1.
- KK677 and KTJJT are both two pair. Their first cards both have the same label, but the second card of KK677 is stronger (K vs T), so KTJJT gets rank 2 - and KK677 gets rank 3.
- T55J5 and QQQJA are both three of a kind. QQQJA has a stronger first card, so it gets rank 5 and T55J5 gets rank 4.
Now, you can determine the total winnings of this set of hands by adding up the result of multiplying each hand's bid with its rank (765 * 1 + 220 * 2 + 28 * 3 + 684 * 4 + 483 * 5). So the total winnings in this example are 6440.

Find the rank of every hand in your set. What are the total winnings?

In [92]:
with open("input.txt","r") as f:
    lines = f.readlines()

In [116]:
test_lines = [
"32T3K 765",
"T55J5 684",
"KK677 28",
"KTJJT 220",
"QQQJA 483"
]

In [87]:
card_list = ["2","3","4","5","6","7","8","9","T","J","Q","K","A"]
hands_list = []
for line_num, line in enumerate(lines):
    hand,bid = line.split(" ")
    hand_list = [0,0,0,0,0,0,0,0,0,0,0,0,0] 
    card_nums = []

    for card in hand:
        for i,base_card in enumerate(card_list):
            if card==base_card:
                hand_list[i]+=1
                card_nums.append(i)
    biggest_count = 0
    second_biggest_count = 0
    two_pair_flag =0
    for card_count in hand_list:
        if card_count==2 and card_count==biggest_count:
            two_pair_flag = 1
        if card_count>biggest_count:
            second_biggest_count = biggest_count
            biggest_count = card_count
        if (card_count< biggest_count) and (card_count>second_biggest_count):
            second_biggest_count = card_count
        
    if biggest_count == 5:
        hand_type = 6
    elif biggest_count == 4:
        hand_type = 5
    elif (biggest_count == 3) and (second_biggest_count == 2):
        hand_type = 4
    elif biggest_count == 3:
        hand_type = 3
    elif two_pair_flag == 1:
        hand_type = 2
    elif biggest_count == 2:
        hand_type = 1
    elif biggest_count == 1:
        hand_type = 0
    card_nums.append(int(bid))
    card_nums.append(hand_type)
    hands_list.append(card_nums)

In [85]:
import pandas as pd
card_df = pd.DataFrame(hands_list,columns=["card1","card2","card3","card4","card5","bid","hand_type"]).sort_values(["hand_type","card1","card2","card3","card4","card5"],ascending=True).reset_index(drop=True).reset_index()
card_df["winnings"] = (card_df["index"]+1)*card_df["bid"]
card_df

     index  card1  card2  card3  card4  card5  bid  hand_type  winnings
0        0      0      1      8      7     11  678          0       678
1        1      0      2      7      1      5  575          0      1150
2        2      0      3      2      4      7  721          0      2163
3        3      0      3     11      6      9  441          0      1764
4        4      0      4     11     10      8  978          0      4890
..     ...    ...    ...    ...    ...    ...  ...        ...       ...
995    995     12     12      8     12     12    3          5      2988
996    996     12     12      9     12     12  317          5    316049
997    997     12     12     12      5     12  540          5    538920
998    998     12     12     12     12      2  276          5    275724
999    999      9      9      9      9      9  145          6    145000

[1000 rows x 9 columns]

In [86]:
card_df.winnings.sum()

249483956

--- Part Two ---

To make things a little more interesting, the Elf introduces one additional rule. Now, J cards are jokers - wildcards that can act like whatever card would make the hand the strongest type possible.

To balance this, J cards are now the weakest individual cards, weaker even than 2. The other cards stay in the same order: A, K, Q, T, 9, 8, 7, 6, 5, 4, 3, 2, J.

J cards can pretend to be whatever card is best for the purpose of determining hand type; for example, QJJQ2 is now considered four of a kind. However, for the purpose of breaking ties between two hands of the same type, J is always treated as J, not the card it's pretending to be: JKKK2 is weaker than QQQQ2 because J is weaker than Q.

Now, the above example goes very differently:

```
32T3K 765
T55J5 684
KK677 28
KTJJT 220
QQQJA 483
```

- 32T3K is still the only one pair; it doesn't contain any jokers, so its strength doesn't increase.
- KK677 is now the only two pair, making it the second-weakest hand.
- T55J5, KTJJT, and QQQJA are now all four of a kind! T55J5 gets rank 3, QQQJA gets rank 4, and KTJJT gets rank 5.
With the new joker rule, the total winnings in this example are 5905.

Using the new joker rule, find the rank of every hand in your set. What are the new total winnings?

In [136]:
additional_test_lines = [
"AJJJJ 1",
"AAJJJ 2",
"AAAJJ 3",
"AAAAJ 4",
"AAAAA 5",
"ATTTJ 6",
"ATQQJ 7",
"ATQKJ 8",
"JJJJJ 9",
"AAQQJ 10",
"AAJTT 11",
"AJJTK 12",
"AAKKT 13"
]

In [144]:
card_list = ["J","2","3","4","5","6","7","8","9","T","Q","K","A"]
hands_list = []
for line_num, line in enumerate(lines):
    hand,bid = line.split(" ")
    hand_list = [0,0,0,0,0,0,0,0,0,0,0,0,0] 
    card_nums = []

    for card in hand:
        for i,base_card in enumerate(card_list):
            if card==base_card:
                hand_list[i]+=1
                card_nums.append(i)
    biggest_count = 0
    second_biggest_count = 0
    two_pair_flag =0
    jack_count = hand_list[0]
    for card_count in hand_list:
        if card_count==2 and card_count==biggest_count:
            two_pair_flag = 1
        if card_count>biggest_count:
            second_biggest_count = biggest_count
            biggest_count = card_count
        if (card_count< biggest_count) and (card_count>second_biggest_count):
            second_biggest_count = card_count
    if biggest_count == 5:
        hand_type = 6
    elif biggest_count == 4:
        if jack_count > 0:
            hand_type=6
        else:
            hand_type=5
    elif (biggest_count == 3) and (second_biggest_count == 2):
        if jack_count>0:
            hand_type=6
        else:
            hand_type = 4 
    elif biggest_count == 3:
        if jack_count>0:
            hand_type = 5
        else:
            hand_type = 3 
    elif two_pair_flag == 1:
        if jack_count==2:
            hand_type=5
        elif jack_count==1:
            hand_type=4
        else:
            hand_type = 2 
    elif biggest_count == 2:
        if jack_count> 0:
            hand_type=3
        else:
            hand_type = 1
    elif biggest_count == 1:
        if jack_count > 0:
            hand_type= 1
        else:
            hand_type = 0
    card_nums.append(int(bid))
    card_nums.append(hand_type)
    hands_list.append(card_nums)

In [145]:
import pandas as pd
card_df = pd.DataFrame(hands_list,columns=["card1","card2","card3","card4","card5","bid","hand_type"]).sort_values(["hand_type","card1","card2","card3","card4","card5"],ascending=True).reset_index(drop=True).reset_index()
card_df["winnings"] = (card_df["index"]+1)*card_df["bid"]
card_df

     index  card1  card2  card3  card4  card5  bid  hand_type  winnings
0        0      1      2      9      8     11  678          0       678
1        1      1      3      8      2      6  575          0      1150
2        2      1      4      3      5      8  721          0      2163
3        3      1      5     11     10      9  978          0      3912
4        4      1      6      4      8      7  169          0       845
..     ...    ...    ...    ...    ...    ...  ...        ...       ...
995    995      8      0      0      8      8  823          6    819708
996    996     10      0     10      0     10  761          6    758717
997    997     10     10      0     10     10  231          6    230538
998    998     12      0     12      0     12  861          6    860139
999    999     12     12      0     12     12  317          6    317000

[1000 rows x 9 columns]

In [146]:
card_df.winnings.sum()

252137472